version: "3"

services: 
    coursematerial:
        image: devopsdockeruh/coursepage
        ports: 
            - 4000:80
        container_name: coursematerial
    watchtower:
        image: containrrr/watchtower
        environment: 
            - WATCHTOWER_POLL_INTERVALL=60 # Poll every 60 secs
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        container_name: watchtower