name: Release DevOps with Docker # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches: 
      - master

# Jon called build runs-on ubuntu-latest
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repo (the actions don't actually need this since they use the repo context anyway)
    - uses: actions/checkout@v2

    # We need to login so we can later push the image without issues
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # Builds devopsdockeruh/docker-hy.github.io
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: devopsdockeruh/coursepage:latest